### ISSUE TITLE
error message "please install fasd" on login 

### ISSUE THREAD

**Issue by GaryFurash** [oh-my-fish/plugin-fasd#14]
"🍒  Please install 'fasd' first!"

however, I do have FASD installed AND it does work (I can use f and z)

**Comment by bobthecow** [comment]
That just means it can't find `fasd` while starting up. Is the `fasd` binary added to your path after OMF init?

**Comment by simnalamburt** [comment]
Closing this issue since it cannot be solved in the side of plugin-fasd.
