### ISSUE TITLE
Lockup on fish 3.0

### ISSUE THREAD

**Issue by krobelus** [oh-my-fish/plugin-fasd#15]
When using fish-shell/fish-shell@8730b482a7e383d9beb6b5195f709b43dc332530 or later, the changes in ee6c646ef704da5ba70a6b9898da13ad2059be88 cause fish to freeze completely. Reverting the latter fixes it for me.

Reproduce the issue by creating a file `prompt.fish`
```fish
function fish_prompt
  echo | source
end
```

Then execute `source prompt.fish` from a shell

**Comment by faho** [comment]
Hi! 

I think this should be fixed via 4a3ac6e91ec415bfe536f722a71903d9a67bb10d in fish-shell/fish-shell (fish-shell/fish-shell@4a3ac6e), so the upcoming 3.0.1 release should fix it. If anyone of you wants to test, build the Integration_3.0.1 branch (https://github.com/fish-shell/fish-shell/tree/Integration_3.0.1).

**Comment by krobelus** [comment]
Awesome, thanks!
