### ISSUE TITLE
Interactive mode does not work

### ISSUE THREAD

**Issue by ryanbahneman** [oh-my-fish/plugin-fasd#8]
Trying to use interactive mode with fasd fails and leaves a floating version of fasd in the background.

e.g. "zz some_dir"

Fasd prints out the options then a "mysterious"  return arrow:
<img width="111" alt="screen shot 2016-03-29 at 2 38 32 pm" src="https://cloud.githubusercontent.com/assets/920304/14124736/095e7c00-f5bc-11e5-92a9-bc7a58759214.png">

I was also having this issue when I tried to integrate fasd into fish via the config.fish file.

**Comment by simnalamburt** [comment]
Closed by #12
